config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  get 'products/auto_complete', to: 'products#autocomplete'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products, :categories, :orders

  root 'products#index'

  post 'products/search', to: 'products#search', as: :search_product

  post 'collection', to: 'collections#add_to_collection', as: :add_to_collection

  get 'products/collection' => 'products#collection'

  get 'user/collection' => 'collections#show'

  post 'products/review' => 'reviews#create_review'

  post 'products/show/order' => 'products#order'

end

app/views/shared/_banner.html.erb
<!--BANNER START-->
<%= audio_tag "When The Love Falls - Yiruma.mp3", id: "sound", class: "audio-to-play", autoplay: true %>

<div class="kode-inner-banner">
  <div class="banner-overlay"></div>
  <div class="kode-page-heading">
  </div>
</div>

<div class="container">
  <div class="banner-search">
    <div class="row">
      <div class="col-md-2">
        <h2>Search Products</h2>
      </div>

      <%= form_tag search_product_path do %>
          <div class="col-md-8">
            <%= text_field_tag :query, params[:query], class: "form-control", id: "product_search", autocomplete: "off", placeholder: 'Search' %>
            <!--<input type="text" placeholder="Enter Your Title" name="query" id="book_search">-->
          </div>
          <div class="col-md-2">
            <%= submit_tag 'Search' %>
          </div>
      <% end %>
    </div>
  </div>
</div>

<!--BANNER END-->
<script type="text/javascript" charset="utf-8">
  $("#product_search").typeahead({
    name: "product",
    hint: null,
    highlight: null,
    limit: 10,
    remote: "/products/auto_complete?query=%QUERY"
  });
</script>

<style>
  .tt-hint {
    display: none;
  }

  .twitter-typeahead {
    width: 100%;
  }

  #book_search {
    background-color: #fff !important;
    width: 100%;
    color: #2b2b2b;
    border-radius: 0px;
  }

  .tt-dropdown-menu {
    background-color: #ffffff;
    padding: 15px;
    border-bottom: 0 none;
    box-shadow: 0 1px 5px rgba(0, 0, 0, 0.46);
    width: 100%;
  }

  .tt-suggestion p {
    padding: 8px 0px;
    margin-bottom: 2px;
    /*border-bottom: 1px solid #333333;*/
  }
</style>

app/views/shared/_copyright.html.erb
<div class="copyrights">
  <div class="container">
    <p>Copyrights © 2015-16 Sannie & Jolene. All rights reserved</p>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <!--TEXT WIDGET START-->
      <div class="col-md-3">
        <div class="widget widget-text">
          <h2>Contact</h2>
          <ul>
            <li><i class="fa fa-tags"></i>
              <p>Ngõ 34A - Lý Nam Đế - Hoàn Kiếm - Hà Nội</p></li>
            <li><i class="fa fa-phone"></i>
              <p>097 975 83 83</p></li>

          </ul>
        </div>
      </div>
      <!--TEXT WIDGET END-->
      <!--TWITTER WIDGET START-->
      <div class="col-md-3">
        <div class="widget widget-text">
          <h2>Map</h2>
          <div class="_5bl1 _4nq9"><a href="#" rel="dialog" ajaxify="https://fbexternal-a.akamaihd.net/map_tile.php?v=18&x=26018&y=14424&z=15&language=vi_VN&theme=undefined" role="button" class=""><div class="_a3e _5bld"><img class="_a3f img" alt="" src="https://fbexternal-a.akamaihd.net/static_map.php?v=18&amp;size=341x200&amp;zoom=15&amp;markers=21.033061989377%2C105.84450602531&amp;language=vi_VN" width="341" height="200"></div></a></div>
        </div>
      </div>
      <!--TWITTER WIDGET END-->
      <!--CATEGORY WIDGET START-->
      <div class="col-md-3">
        <div class="widget widget-categories">
          <img alt="Fb" class="left" src="http://www.iconarchive.com/download/i49146/yootheme/social-bookmark/social-facebook-box-blue.ico" style="max-width: 40px">
          <a href="https://www.facebook.com/sanniejolene/?fref=ts" target="_blank">Facebook</a>
        </div>
      </div>
      <!--CATEGORY WIDGET END-->
      <!--NEWSLETTER START-->
      <div class="col-md-3">
        <div class="widget widget-newletter">
          <p>Đăng kí để nhận thông tin từ Sannie & Jolene</p>
          <input type="text" placeholder="E-mail ID">
          <button>Register</button>
        </div>
      </div>
      <!--NEWSLETTER START END-->
    </div>
  </div>
</footer>

app/views/shared/_head.html.erb
<head>
    <title>Cafe</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title><%= @title %></title>
  <!-- CUSTOM STYLE -->
  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
</head>

app/views/shared/_header.html.erb
<!--HEADER START-->
<header>
  <div class="top-strip">
    <div class="container">
      <div class="site-info">
        <ul class="personal">
          <% if current_user %>
          <% if current_user.avatar.url %>
          <li><%= link_to image_tag(current_user.avatar.thumb.url), edit_user_registration_path %></li>
          <% else %>
          <li><%= link_to image_tag('https://cdn4.iconfinder.com/data/icons/small-n-flat/24/user-alt-128.png'), edit_user_registration_path %></li>
          <% end %>
          <li><%= link_to current_user.email, edit_user_registration_path %></li>
          <li>
            <%= link_to '<i class="fa fa-heart"></i>'.html_safe, user_collection_path %>
          </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
  <!--Search Overlay Box Starts -->
  <div id="kode_search_box" class="kode_search_box">
    <form class="kode_search_box-form">
      <input class="kode_search_box-input" type="search" placeholder="Search..."/>
      <button class="kode_search_box-submit" type="submit">Search</button>
    </form>
    <span class="kode_search_box-close"></span>
  </div><!-- /kode_search_box -->
  <div class="overlay"></div>
  <div class="logo-container">
    <div class="container">
      <div class="kode-navigation">
        <ul style="font-size: 24px">
          <li><%= link_to 'Home', root_path %></li>
          <li><a href="about-us.html">About Us</a></li>
          <li class="menu-item kode-parent-menu last"><a href="">Menu</a>
            <ul class="dl-submenu">
              <% @categories.each do |category| %>
              <li><%= link_to category.name, category_path(id: category.id) %></li>
              <% end %>
            </ul>
          </li>
          <li class="last"><a href="contact-us.html">Contact Us</a></li>
          <% #binding.pry %>
          <% if user_signed_in? %>
            <li class="menu-item kode-parent-menu last"><a href="">Profile</a>
              <ul class="dl-submenu">
                <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
                <li><%= link_to 'Order', orders_path %></li>
                <li><%= link_to 'Sign out', destroy_user_session_path, method: "delete" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to 'Sign in', user_session_path %></li>
          <% end %>

        </ul>
      </div>
      <div id="kode-responsive-navigation" class="dl-menuwrapper">
        <button class="dl-trigger">Open Menu</button>
        <ul class="dl-menu">
          <li><a href="index.html">Home</a></li>
          <li><a href="about-us.html">About Us</a></li>
          <li class="menu-item kode-parent-menu last"><a href="">Products</a>
            <ul class="dl-submenu">
              <li><a href="book-listing.html">Cakes</a></li>
              <li><a href="book-listing-1.html">Drinks</a></li>
            </ul>
          </li>
          <li class="last"><a href="contact-us.html">Contact Us</a></li>
        </ul>
      </div>
    </div>
  </div>
</header>
<!--HEADER END-->

app/views/shared/_new_letter.html.erb
<!--NEWSLETTER START-->
<section class="kode-newsletters">
  <div class="container">
    <!--SECTION CONTENT START-->
    <div class="section-content white">
      <h2>Subscribe to our Newsletter for the latest news.</h2>
      <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem
        aperiam.ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores
        eos qui ratione voluptatem sequi nesciunt.</p>
    </div>
    <!--SECTION CONTENT END-->
    <div class="input-container">
      <input type="text" placeholder="Subscribe us">
      <button>Subcribe</button>
    </div>
  </div>
</section>
<!--NEWSLETTER END-->

app/views/shared/_sidebar.html.erb
 <div class="col-md-3 sidebar">
    <div class="widget widget-search">
      <h2>Search</h2>
      <%= form_tag search_product_path do %>
          <div class="input-container">
            <%= text_field_tag :query, params[:query], class: "form-control", id: "product_search", autocomplete: "off", placeholder: 'Search Product' %>
            <button type="submit" class="fa fa-search"></button>
          </div>
      <% end %>
    </div>
    <!--CATEGORY WIDGET START-->
    <div class="widget widget-categories">
      <h2>Categories</h2>
      <ul>
        <% @categories.each do |category| %>
            <li><%= link_to category.name, category_path(id: category.id) %></li>
        <% end %>
      </ul>
    </div>
    <!--CATEGORY WIDGET END-->
    <div class="widget widget-new-arrival">
      <h2>New Arrival</h2>
      <ul>
        <% @new_arrivals.each do |product| %>
            <li>
              <div class="new-arrival">
                <div class="kode-thumb">
                  <%= link_to product_path(product) do %>
                      <%= image_tag product.image %>
                  <% end %>
                </div>
                <div class="kode-text">
                  <h3><%= link_to product.name, product_path(product) %></h3>
                </div>
              </div>
            </li>
        <% end %>
      </ul>
    </div>
    <div class="widget widget-new-arrival">
      <h2>Best Sellers</h2>
      <ul class="bxslider">
        <% @best_sellers.shuffle.each_slice(3).each do |products| %>
            <li>
              <% products.each do |product| %>
                  <div class="new-arrival">
                    <div class="kode-thumb">
                      <%= link_to (image_tag product.image), product_path(product) %>
                    </div>
                    <div class="kode-text">
                      <h3><%= link_to product.name, product_path(product) %></h3>
                      <p><%= product.price %> VND</p>
                    </div>
                  </div>
              <% end %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>

  <script type="text/javascript" charset="utf-8">
    $("#product_search").typeahead({
      name: "product",
      hint: null,
      highlight: null,
      limit: 10,
      remote: "/products/auto_complete?query=%QUERY"
    });
  </script>

  <style>
    .widget-search .input-container button{
      position:absolute;
      right:1px;
      left:auto;
      top:1px;
      height:42px;
      font-size:14px;
      color:grey;
      background-color:#f6f7f8;
    }
    .tt-hint {
      display: none;
    }

    .twitter-typeahead {
      width: 100%;
    }

    #book_search {
      background-color: #fff !important;
      width: 100%;
      color: #2b2b2b;
      border-radius: 0px;
    }

    .tt-dropdown-menu {
      background-color: #ffffff;
      padding: 15px;
      border-bottom: 0 none;
      box-shadow: 0 1px 5px rgba(0, 0, 0, 0.46);
      width: 100%;
    }

    .tt-suggestion p {
      padding: 8px 0px;
      margin-bottom: 2px;
      /*border-bottom: 1px solid #333333;*/
    }
  </style>