config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  :omniauth_callbacks => 'users/omniauth_callbacks'
  }

  get 'products/auto_complete', to: 'products#autocomplete'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products, :categories, :orders

  root 'products#index'

  post 'products/search', to: 'products#search', as: :search_product

  post 'collection', to: 'collections#add_to_collection', as: :add_to_collection

  get 'products/collection' => 'products#collection'

  get 'user/collection' => 'collections#show'

  post 'products/review' => 'reviews#create_review'

  post 'products/show/order' => 'products#order'

end

app/models/product.rb
# == Schema Information
#
# Table name: products
#
#  id         :integer          not null, primary key
#  name       :string
#  about      :text
#  price      :integer
#  image      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Product < ActiveRecord::Base
  searchkick match: :word_start, searchable: [:name]

  has_many :products_categories
  has_many :categories, through: :products_categories

  enum is_new: [:new_arrival, :best_seller]

  has_many :product_collections
  has_many :collections, through: :product_collections

  has_many :order_products
  has_many :orders, through: :order_products

  has_many :reviews
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :set_products, only: [:collection,:show]

  # GET /products
  # GET /products.json
  def index
    @products = Product.order('created_at ASC').page(params[:page]).per(9)
  end

  #POST "products/search/", to: "products#search"
  def search
    @products = Product.search(params[:query], fields: [:name])
    respond_to do |format|
      format.html { render :index }
    end
  end

  def autocomplete
    respond_to do |format|
      format.html
      format.js

      format.json {
        render json: Product.search(params[:query], {
            fields: ["name"],
            limit: 10,
            load: false,
            misspellings: {below: 1}
        }).map(&:name)
      }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def order
    @product = Product.find(params[:product_id])

    @categories = Category.all
    @new_arrivals = Product.new_arrival
    @best_sellers = Product.best_seller

    @order = Order.create(quantity: params[:quantity], user_id: params[:user_id])

    @order.products << @product
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_products
    @products = Product.all
  end

  def set_product
    @product = Product.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def product_params
    params.require(:product).permit(:name, :about, :price, :image)
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
  <%= form_for(@product) do |f| %>
      <% if @product.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>
            <ul>
              <% @product.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
              <% end %>
            </ul>
          </div>
      <% end %>

      <div class="field">
        <%= f.label :name %><br>
        <%= f.text_field :name %>
      </div>
      <div class="field">
        <%= f.label :price %><br>
        <%= f.number_field :price %>
      </div>
      <div class="field">
        <%= f.label :image %><br>
        <%= f.text_field :image %>
      </div>
      <div class="field">
        <%= f.label :about %><br>
        <%= f.text_area :about %>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
  <% end %>

app/views/products/collection.html.erb
<% current_user.collection.products.each do |product| %>
    <div class="col-md-4 col-sm-6">
      <div class="books-listing-3">
        <div class="kode-thumb">
          <%= link_to (image_tag product.image), product_path(id: product.id) %>
        </div>

        <div class="kode-text">
          <p class="price"><%= product.price %><span style="text-decoration: none; color:orange">VND</span></p>
          <h3><%= link_to truncate(product.name, length: 18), product_path(id: product.id) %></h3>
          <div class="kode-caption">
            <p><%= truncate(product.about, length: 200) %></p>

            <%= form_tag add_to_collection_path, remote: true, id: "form-add-to-collection" do %>
                <%= hidden_field_tag :product_id, product.id %>
                <% if current_user %>
                    <a class="btn-book-like <%= 'active' if current_user.collection.products.include?(product) %>" >
                      <i class="fa fa-heart"></i></a>
                    <a><i class="fa fa-cart-plus"></i></a>
                    <a><i class="fa fa-link"></i></a>
                <% end %>
            <% end %>

          </div>
        </div>
      </div>
    </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<% @title="Home" %>
<body>

<div class="col-md-9">
  <%= paginate(@products) %>
  <br>

  <div class="row">
    <% @products.each do |product| %>
        <div class="col-md-4 col-sm-6">
          <div class="books-listing-3">
            <div class="kode-thumb">
              <%= link_to (image_tag product.image), product_path(id: product.id) %>
            </div>
            <div class="kode-text">
              <p class="price"><%= product.price %><span style="text-decoration: none; color:orange">VND</span></p>
              <h3><%= link_to truncate(product.name, length: 18), product_path(id: product.id) %></h3>
              <div class="kode-caption">
                <p><%= truncate(product.about, length: 200) %></p>

                <%= form_tag add_to_collection_path, remote: true, id: "form-add-to-collection" do %>
                    <%= hidden_field_tag :product_id, product.id %>
                    <% if current_user %>
                        <a class="btn-book-like <%= 'active' if current_user.collection.products.include?(product) %>">
                          <i class="fa fa-heart"></i></a>
                        <a class="" data-toggle="modal" data-target="#<%= product.id %>"><i class="fa fa-cart-plus"></i></a>
                    <% end %>
                <% end %>
              </div>
            </div>
          </div>
          <div id="<%= product.id %>" class="modal fade" role="dialog">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Order Detail</h4>
                </div>
                <%= form_tag products_show_order_path do %>
                    <div class="modal-body">
                      <%= product.name %>
                      <%= number_field_tag :quantity, nil, min: 1, placeholder: 'Số lượng', :class => 'form-control' %>
                      <%= hidden_field_tag :product_id, product.id %>
                      <% if user_signed_in? %>
                          <%= hidden_field_tag :user_id, current_user.id %>
                      <% end %>
                    </div>
                    <div class="modal-footer">
                      <%= submit_tag 'Order', :class => 'btn btn-default' %>
                    </div>
                <% end %>
              </div>
            </div>
          </div>
        </div>
    <% end %>
  </div>

  <br>
  <%= paginate(@products) %>
</div>


<script type="text/javascript" charset="utf-8">
  $(".btn-book-like").click(function () {
    $(this).parent().submit();
    $(this).toggleClass('active');
  })

  $('.test').click(function () {
    alert('Xin chao')
  })

  $(document).ready(function () {
    (function () {
      "use strict";
      if (window.location && window.location.hash) {
        if (window.location.hash === '#_=_') {
          window.location.hash = '';
          history.pushState('', document.title, window.location.pathname); // nice and clean
        }
      }
    }());
  });
</script>
</body>
</html>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/order.html.erb
<%- model_class = Order -%>
<div class="col-md-9">
  <div class="page-header">
    <h1>Order</h1>
  </div>
  <table class="table table-striped">
    <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:product) %></th>
      <th><%= model_class.human_attribute_name(:quantity) %></th>
      <th><%= model_class.human_attribute_name(:delivered_at) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
    </tr>
    </thead>
    <tbody>
    <% @order.products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= @order.quantity %></td>
          <td><%= @order.delivered_at %></td>
          <td><%= @order.user.email %></td>
          <td><%= @order.created_at %></td>
        </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/products/show.html.erb
<body xmlns="http://www.w3.org/1999/html">
<!--CONTENT START-->
<!--TOP AUTHERS START-->
<div class="col-md-9">
  <div class="lib-book-detail">
    <div class="row">
      <div class="col-md-5">
        <div class="kode-thumb">
          <%= image_tag @product.image %>
        </div>
      </div>
      <div class="col-md-7">
        <div class="kode-text">
          <h1><%= @product.name %></h1>
          <div class="product-review">
            <div class="rating">
              <span>☆</span><span>☆</span><span>☆</span><span>☆</span><span>☆</span>
            </div>
          </div>
          <div class="product-price">
            <h4><%= @product.price %> VND</h4>
          </div>
          <div class="book-text">
            <p><%= @product.about %></p>
          </div>
          <a href="#" class="add-to-cart">Add To Cart</a>
          <a class="add-to-cart <%= "like-btn-active" if (current_user && (current_user.collection.products.include? @product)) %> "
             id="js-btn-add-to-wishlist" product-id="<%= @product.id %>">
            Add To Wishlist
          </a>
        </div>
      </div>
    </div>
  </div>

  <div class="product-review-tabs">
    <ul class="nav nav-tabs" role="tablist">
      <h1>Bình luận</h1>
    </ul>
    <div class="tab-content">
      <div class="kode-comments">
        <% if @product.reviews == [] %>
            <p>Chưa có bình luận nào</p>
        <% else %>
            <ul>
              <% @product.reviews.each do |review| %>
                  <li>
                    <div class="kode-thumb">
                      <%= image_tag review.user.avatar.url %>
                    </div>
                    <div class="kode-text">
                      <h4><%= review.user.email %></h4>
                      <p><%= review.text %></p>
                    </div>
                  </li>
              <% end %>
            </ul>
        <% end %>
      </div>
    </div>
  </div>

</div>

<% if user_signed_in? %>
    <div class="col-md-9">
      <%= form_tag products_review_path, remote: true do %>
          <div class="">
            <%= text_field_tag :text, nil, placeholder: 'Viết bình luận', :class => 'form-control' %>
            <%= hidden_field_tag :user_id, current_user.id %>
            <%= hidden_field_tag :product_id, @product.id %>
          </div>
          <br>
          <div class="col-md-offset-10" id="submit-review">
            <%= submit_tag 'Bình luận', :class => 'btn btn-default' %>
          </div>
      <% end %>
    </div>
<% end %>

<!--CONTENT END-->
<script type="text/javascript" charset="utf-8">
  $("#js-btn-add-to-wishlist").click(function () {
    $.ajax({
      url: "//" + location.host + "/collection",
      method: "POST",
      data: {
        book_id: $(this).attr('book-id')
      },
      dataType: "json",
      success: function (data) {
        console.log('success');
        return $("#js-btn-add-to-wishlist").toggleClass('like-btn-active');
      },
      error: function (jqXHR, textStatus) {
        return alert("Request failed: " + textStatus);
      }
    });
  });

  $('#submit-review').click(function () {
    location.reload();
  })
</script>
</body>
</html>